### ISSUE TITLE
Blood glucose: different units in Nightscout depending on entry composition

### ISSUE THREAD

**Issue by bjornoleh** [jwoglom/dm2nsc#5]
Hi,

Imported blood glucose readings get different units in Nightscout depending on entry composition (combination of BG, insulin and carbs). When an entry contains blood glucose readings only, the BG value is reported as mg/dL, but should be in mmol/L. The values are correctly positioned on the curve, only the numbers in the textboxes are wrong.

I use **mmol/L** as BG units in both Diabetes:M and Nightscout.

Example (please see uploaded image for details):

BG Check entry with blood glucose only:
Reads 148 [mg/dL]
Should read 148/18 = 8,2 [mmol/L]
With entries consisting of any combination of BG + insulin or carbs, the text is correct.

It seems the problems are independent of whether the entries are classified as "BG Check" or "Meal Bolus", and this designation seems somewhat random.

I managed to fix this by messing with getdata.py. I believe line 76 is the culprit, as I could not figure out what to substitute `entry["us_units"]` with in my case. I would expect something like "metric_units" would do the trick, but unfortunately, no.

My workaround was this:

`def to_mmol(mmol):
	return (mmol)`

`glucose = entry["glucoseInCurrentUnit"] if entry["glucoseInCurrentUnit"] and entry["us_units"] else to_mmol(entry["glucose"])`

`"units": "mmol" # changed from /"units": "mg/dL"/`

I have very limited programming skills, and was happy to find a workaround. This was probably not the best solution, but it might just help someone like me.

![BG_Check](https://user-images.githubusercontent.com/63544115/81167586-be127080-8f95-11ea-9256-8177d41886b0.png)

**Comment by bjornoleh** [comment]
Edit: it appears I have not made a successful workaround after all. The values which were shown as mmolx18 are now ok, but the ones which were correct are displayed as mmol/18.

I would be grateful if someone could help me wiyth this issue!

Thanks

**Comment by jwoglom** [comment]
Diabetes-M has changed how they handle mg/dl vs mmol/l units in the past, so this doesn't surprise me. I use mg/dl units throughout, so I might not be able to test this as thoroughly as you.

What might help is if you are able to get an example BG/carbs entry from Diabetes-M. You can get this by adding a `print(entry)` line inside the for loop in convert_nightscout(), i.e. line 50: https://github.com/jwoglom/dm2nsc/blob/master/getdata.py#L50 From this we can figure out what fields change when you switch units and modify the logic accordingly.

Here is a sample entry for me:
```
entry_id: xxxx
user_id: xxxx
input_id: xxxx
photo_id: 0
photo_timestamp: 0
device_hash: xxxx
last_modified: 1588782036649
deleted: false
entry_time: 1588782000000
glucose: 6.660007
carbs: 100
proteins: 0
fats: 0
calories: 0
carb_bolus: 10
correction_bolus: 0
extended_bolus: 0
extended_bolus_duration: 0
basal: 0
basal_is_rate: false
bolus_insulin_type: 1
basal_insulin_type: 1
weight_entry: 0
weight: 72.574776
category: 2
carb_ratio_factor: 6
insulin_sensitivity_factor: 2.2200022
notes: "notes field"
is_sensor: false
pressure_sys: 0
pressure_dia: 0
pulse: 0
injection_bolus_site: -1
injection_basal_site: -1
finger_test_site: -1
ketones: 0
timezone: "America/New_York"
exercise_index: 0
exercise_comment: ""
exercise_duration: 0
medications: ""
food: ""
server_date_created: 1588782037372
server_date_modified: 1588782037260
flags: 0
hba1c: 0
cholesterol_total: 0
cholesterol_ldl: 0
cholesterol_hdl: 0
us_units: false
triglycerides: 0
microalbumin_test_type: 0
microalbumin: 0
creatinine_clearance: 0
egfr: 0
cystatin_c: 0
albumin: 0
creatinine: 0
calcium: 0
total_protein: 0
sodium: 0
potassium: 0
bicarbonate: 0
chloride: 0
alp: 0
alt: 0
ast: 0
bilirubin: 0
bun: 0
photo_last_updated: 0
medications_list: []
food_list: []
glucoseInCurrentUnit: 120
carbsInCurrentUnit: 100
weightEntryInCurrentUnit: 0
hba1cInCurrentUnit: 0
cholesterol_totalInCurrentUnit: 0
cholesterol_ldlInCurrentUnit: 0
cholesterol_hdlInCurrentUnit: 0
ketonesInCurrentUnit: 0
triglyceridesInCurrentUnit: 0
```
And a screenshot from the analytics.diabetes-m.com web UI:
![image](https://user-images.githubusercontent.com/192620/81202114-1b0d2700-8f94-11ea-8795-4792386e6b8b.png)

**Comment by bjornoleh** [comment]
Thank you so much for your reply!

I got the list as you suggested, using the same getdata.py version as with the examples given in the first post, without the unsuccessful workaround.

These are the two last entries, one with 'glucose': 6.4 only, the second one with 'glucose': 3.9 and 'carbs': 2.5.

They seem to be formatted the same way in the Diabetes-M export, but are displayed differently in Nightscout.

![2_entries](https://user-images.githubusercontent.com/63544115/81210937-e8365380-8fd2-11ea-8ca6-8c5dd56e13cf.png)

I see there is a `'us_units': False` parameter, this could possibly be used somehow?

```
'entry_id':   xxxxxx441
'user_id': xxxxxx
'input_id': xxxxxxx500000
'photo_id': 0
'photo_timestamp': 0
'device_hash': xxxxx
'last_modified': 1588780559189
'deleted': False
'entry_time': 1588780500000
'glucose': 6.4
'carbs': 0.0
'proteins': 0.0
'fats': 0.0
'calories': 0.0
'carb_bolus': 0.0
'correction_bolus': 0.0
'extended_bolus': 0.0
'extended_bolus_duration': 0
'basal': 0.0
'basal_is_rate': False
'bolus_insulin_type': 13
'basal_insulin_type': 9
'weight_entry': 0.0
'weight': 20.0
'category': 6
'carb_ratio_factor': 40.0
'insulin_sensitivity_factor': 10.0
'notes': 'test'
'is_sensor': False
'pressure_sys': 0
'pressure_dia': 0
'pulse': 0
'injection_bolus_site': -1
'injection_basal_site': -1
'finger_test_site': -1
'ketones': 0.0
'timezone': 'Europe/Oslo'
'exercise_index': 0
'exercise_comment': ''
'exercise_duration': 0
'medications': ''
'food': ''
'server_date_created': 1588780559823
'server_date_modified': 1588780559791
'flags': 0
'hba1c': 0.0
'cholesterol_total': 0.0
'cholesterol_ldl': 0.0
'cholesterol_hdl': 0.0
'us_units': False
'triglycerides': 0.0
'microalbumin_test_type': 0
'microalbumin': 0.0
'creatinine_clearance': 0.0
'egfr': 0.0
'cystatin_c': 0.0
'albumin': 0.0
'creatinine': 0.0
'calcium': 0.0
'total_protein': 0.0
'sodium': 0.0
'potassium': 0.0
'bicarbonate': 0.0
'chloride': 0.0
'alp': 0.0
'alt': 0.0
'ast': 0.0
'bilirubin': 0.0
'bun': 0.0
'photo_last_updated': 0
'medications_list': []
'food_list': []
'glucoseInCurrentUnit': 6.4
'carbsInCurrentUnit': 0.0
'weightEntryInCurrentUnit': 0.0
'hba1cInCurrentUnit': 0.0
'cholesterol_totalInCurrentUnit': 0.0
'cholesterol_ldlInCurrentUnit': 0.0
'cholesterol_hdlInCurrentUnit': 0.0
'ketonesInCurrentUnit': 0.0
'triglyceridesInCurrentUnit': 0.0}
```


```
'entry_id': xxxxxx009
'user_id': xxxxxx
'input_id': xxxxxxx180000
'photo_id': 0
'photo_timestamp': 0
'device_hash': xxxxx
'last_modified': 1588782211656
'deleted': False
'entry_time': 1588782180000
'glucose': 3.9
'carbs': 2.5
'proteins': 0.0
'fats': 0.0
'calories': 0.0
'carb_bolus': 0.0
'correction_bolus': 0.0
'extended_bolus': 0.0
'extended_bolus_duration': 0
'basal': 0.0
'basal_is_rate': False
'bolus_insulin_type': 13
'basal_insulin_type': 9
'weight_entry': 0.0
'weight': 20.0
'category': 6
'carb_ratio_factor': 30.0
'insulin_sensitivity_factor': 10.0
'notes': '4.2 pil ned i dex'
'is_sensor': False
'pressure_sys': 0
'pressure_dia': 0
'pulse': 0
'injection_bolus_site': -1
'injection_basal_site': -1
'finger_test_site': -1
'ketones': 0.0
'timezone': 'Europe/Oslo'
'exercise_index': 0
'exercise_comment': ''
'exercise_duration': 0
'medications': ''
'food': ''
'server_date_created': 1588782212253
'server_date_modified': 1588782212248
'flags': 0
'hba1c': 0.0
'cholesterol_total': 0.0
'cholesterol_ldl': 0.0
'cholesterol_hdl': 0.0
'us_units': False
'triglycerides': 0.0
'microalbumin_test_type': 0
'microalbumin': 0.0
'creatinine_clearance': 0.0
'egfr': 0.0
'cystatin_c': 0.0
'albumin': 0.0
'creatinine': 0.0
'calcium': 0.0
'total_protein': 0.0
'sodium': 0.0
'potassium': 0.0
'bicarbonate': 0.0
'chloride': 0.0
'alp': 0.0
'alt': 0.0
'ast': 0.0
'bilirubin': 0.0
'bun': 0.0
'photo_last_updated': 0
'medications_list': []
'food_list': []
'glucoseInCurrentUnit': 3.9
'carbsInCurrentUnit': 2.5
'weightEntryInCurrentUnit': 0.0
'hba1cInCurrentUnit': 0.0
'cholesterol_totalInCurrentUnit': 0.0
'cholesterol_ldlInCurrentUnit': 0.0
'cholesterol_hdlInCurrentUnit': 0.0
'ketonesInCurrentUnit': 0.0
'triglyceridesInCurrentUnit': 0.0}

```

**Comment by bjornoleh** [comment]
The same entries in the transated file for Nightscout upload looks like this. Both entries are here given as mg/dL, and I cant see any differences between them? I have been scratching my head about why the different kinds of entries looks differently in the end, but I'm not getting any wiser. To me it looks like a Nightscout issue?


```
'eventType': 'BG   Check'
'created_at': '2020-05-06 17:55:00+02:00'
'carbs': 0.0
'insulin': 0.0
'notes': 'test'
'enteredBy': 'Diabetes-M (dm2nsc)'
'glucose': 115
'glucoseType': 'Finger'
'units': 'mg/dL'
 


'eventType': 'BG Check'
'created_at': '2020-05-06 18:23:00+02:00'
'carbs': 2.5
'insulin': 0.0
'notes': '4.2 pil ned i dex'
'enteredBy': 'Diabetes-M (dm2nsc)'
'glucose': 70
'glucoseType': 'Finger'
'units': 'mg/dL'

**Comment by jwoglom** [comment]
Weird, although I think this may moreso be inconsistent behavior with how Nightscout checks units in the UI rather than a bug. For the BG Check with only glucose information, perhaps the Nightscout UI displays the bg with the *saved unit* (mg/dl) rather than the configured system default unit (mmol/L)? But when there is carb or insulin information, it converts the glucose reading to the system unit?

I wonder what would happen if for the first BG check, instead of storing 'units': 'mg/dL' and 'glucose': 115, you entered 'units': 'mmol' and 'glucose': (whatever the mg/dl->mmol conversion is, as a decimal). Then perhaps Nightscout will display it in the UI properly, and if this is the case then I could patch the logic of adding Nightscout entries to not always convert database fields to mg/dl and keep them as mmol/L for this case.

**Comment by bjornoleh** [comment]
Thanks for the suggestion.

Here are the results from the workaround shown in the first post, using the same entries as before. The units are now in mmol/L.

The exported data are of course the same:

**BG only:**
'glucose': 6.4
'glucoseInCurrentUnit': 6.4
'us_units': False


**BG + carbs:**
'glucose': 3.9
'carbs': 2.5
'glucoseInCurrentUnit': 3.9
'carbsInCurrentUnit': 2.5
'us_units': False

The upload to Nightscout looks like this:

**BG only:**
```
eventType:"BG   Check"
created_at:"2020-05-06T15:55:00.000Z"
notes:"test"
enteredBy:"Diabetes-M (dm2nsc)"
glucose:6.4
glucoseType:"Finger"
units:"mmol"
utcOffset:120}
```


**BG + carbs:**
```
"eventType":"BG   Check"
created_at:"2020-05-06T16:23:00.000Z"
carbs:2.5
notes:"4.2 pil ned i dex"
enteredBy:"Diabetes-M (dm2nsc)"
glucose:3.9
glucoseType:"Finger"
units:"mmol"
utcOffset:120

```


In Nightscout, the results are the "opposite" compared to before the "workaround". Before, BG+carbs was correct, after the workaround BG only was correct. All values are divided by 18.
![2_entries_workaround](https://user-images.githubusercontent.com/63544115/81272701-1dcc5280-904e-11ea-91d0-396bd532d09a.png)


A proper workaround for this would be very welcome! I could possibly manage by trial-and-(mostly)error, but my initial attempts have not been too encouraging.

Thanks!







**BG only:**
```
'entry_id':   xxxx
'user_id': xxxx
'input_id': xxxxxxx500000
'photo_id': 0
'photo_timestamp': 0
'device_hash': xxxx
'last_modified': 1588780559189
'deleted': False
'entry_time': 1588780500000
'glucose': 6.4
'carbs': 0.0
'proteins': 0.0
'fats': 0.0
'calories': 0.0
'carb_bolus': 0.0
'correction_bolus': 0.0
'extended_bolus': 0.0
'extended_bolus_duration': 0
'basal': 0.0
'basal_is_rate': False
'bolus_insulin_type': 13
'basal_insulin_type': 9
'weight_entry': 0.0
'weight': 20.0
'category': 6
'carb_ratio_factor': 40.0
'insulin_sensitivity_factor': 10.0
'notes': 'test'
'is_sensor': False
'pressure_sys': 0
'pressure_dia': 0
'pulse': 0
'injection_bolus_site': -1
'injection_basal_site': -1
'finger_test_site': -1
'ketones': 0.0
'timezone': 'Europe/Oslo'
'exercise_index': 0
'exercise_comment': ''
'exercise_duration': 0
'medications': ''
'food': ''
'server_date_created': 1588780559823
'server_date_modified': 1588780559791
'flags': 0
'hba1c': 0.0
'cholesterol_total': 0.0
'cholesterol_ldl': 0.0
'cholesterol_hdl': 0.0
'us_units': False
'triglycerides': 0.0
'microalbumin_test_type': 0
'microalbumin': 0.0
'creatinine_clearance': 0.0
'egfr': 0.0
'cystatin_c': 0.0
'albumin': 0.0
'creatinine': 0.0
'calcium': 0.0
'total_protein': 0.0
'sodium': 0.0
'potassium': 0.0
'bicarbonate': 0.0
'chloride': 0.0
'alp': 0.0
'alt': 0.0
'ast': 0.0
'bilirubin': 0.0
'bun': 0.0
'photo_last_updated': 0
'medications_list': []
'food_list': []
'glucoseInCurrentUnit': 6.4
'carbsInCurrentUnit': 0.0
'weightEntryInCurrentUnit': 0.0
'hba1cInCurrentUnit': 0.0
'cholesterol_totalInCurrentUnit': 0.0
'cholesterol_ldlInCurrentUnit': 0.0
'cholesterol_hdlInCurrentUnit': 0.0
'ketonesInCurrentUnit': 0.0
'triglyceridesInCurrentUnit': 0.0
```




**BG + carbs:**
```
'entry_id':   xxx
'user_id': xxxx
'input_id': xxxxxx80000
'photo_id': 0
'photo_timestamp': 0
'device_hash': xxxxx
'last_modified': 1588782211656
'deleted': False
'entry_time': 1588782180000
'glucose': 3.9
'carbs': 2.5
'proteins': 0.0
'fats': 0.0
'calories': 0.0
'carb_bolus': 0.0
'correction_bolus': 0.0
'extended_bolus': 0.0
'extended_bolus_duration': 0
'basal': 0.0
'basal_is_rate': False
'bolus_insulin_type': 13
'basal_insulin_type': 9
'weight_entry': 0.0
'weight': 20.0
'category': 6
'carb_ratio_factor': 30.0
'insulin_sensitivity_factor': 10.0
'notes': '4.2 pil ned i dex'
'is_sensor': False
'pressure_sys': 0
'pressure_dia': 0
'pulse': 0
'injection_bolus_site': -1
'injection_basal_site': -1
'finger_test_site': -1
'ketones': 0.0
'timezone': 'Europe/Oslo'
'exercise_index': 0
'exercise_comment': ''
'exercise_duration': 0
'medications': ''
'food': ''
'server_date_created': 1588782212253
'server_date_modified': 1588782212248
'flags': 0
'hba1c': 0.0
'cholesterol_total': 0.0
'cholesterol_ldl': 0.0
'cholesterol_hdl': 0.0
'us_units': False
'triglycerides': 0.0
'microalbumin_test_type': 0
'microalbumin': 0.0
'creatinine_clearance': 0.0
'egfr': 0.0
'cystatin_c': 0.0
'albumin': 0.0
'creatinine': 0.0
'calcium': 0.0
'total_protein': 0.0
'sodium': 0.0
'potassium': 0.0
'bicarbonate': 0.0
'chloride': 0.0
'alp': 0.0
'alt': 0.0
'ast': 0.0
'bilirubin': 0.0
'bun': 0.0
'photo_last_updated': 0
'medications_list': []
'food_list': []
'glucoseInCurrentUnit': 3.9
'carbsInCurrentUnit': 2.5
'weightEntryInCurrentUnit': 0.0
'hba1cInCurrentUnit': 0.0
'cholesterol_totalInCurrentUnit': 0.0
'cholesterol_ldlInCurrentUnit': 0.0
'cholesterol_hdlInCurrentUnit': 0.0
'ketonesInCurrentUnit': 0.0
'triglyceridesInCurrentUnit': 0.0
```

**Comment by jwoglom** [comment]
So does it seem correct to say that if the entry is BG only, we should upload to Nightscout with units: mmol, but if the entry has carbs then we should upload to Nightscout with units: mg/dL? Will that result in the mmol units displaying properly in Nightscout for you?

**Comment by bjornoleh** [comment]
Yes, this appears to be the case.

**Comment by jwoglom** [comment]
@bjornoleh update your repo and give this a try: it should check the DB-M units and update Nightscout accordingly. also, take a look at the edge case for providing either carbs or insulin but not both, to make sure I handled that correctly.

**Comment by bjornoleh** [comment]
Hi, many thanks, now it works!

![image](https://user-images.githubusercontent.com/63544115/81470967-412e0380-91ee-11ea-9732-f94e10d4dc7b.png)

I had to update secret.py as well:
`MMOL_UNITS = 'mmol'`

Perhaps you could ad something like this to sectet.py or README.md:
```
# if  using BG units mmol/L, please add this to secret.py
# MMOL_UNITS = 'mmol'
```

Also, I had to add # (or delete) the lines 52 - 66 as the date example caused an error. This may be obvious for most, but I had to find out :-)

```
# You can do some custom processing here, if necessary. e.x.:
#		if arrow.get("10/3/2017").date() > time.date() and DO_MYSUGR_PROCESSING:
#			author = "mySugr via "+author
#			# basal data is for Lantus
#			if entry["basal"]:
#				out.append({
#					"eventType": "Temp Basal",
#					"absolute": entry["basal"],
#					"notes": notes,
#					"enteredBy": author,
#					"duration": 1440,
#					"reason": "Lantus",
#					"notes": notes
#				})
```


Thanks again for your help!

**Comment by jwoglom** [comment]
Hadn't meant to keep the secret import there, so the import issue should be fixed. Also removed the custom processing since it was mostly an example and it's not needed anyway.
